from pydantic import BaseModel

class All(BaseModel):
    symptoms: str
    # fever: int
    # cough: int
    # sore_throat: int
    # runny_or_stuffy_nose: int
    # muscle_aches: int
    # headache: int
    # fatigue: int
    # mucus_production: int
    # shortness_of_breath: int
    # chest_pain: int
    # nausea: int
    # vomiting: int
    # lightheadedness: int
    # sweating: int
    # sudden_weakness: int
    # numbness_on_one_side_of_the_body: int
    # confusion: int
    # difficulty_speaking: int
    # trouble_seeing_in_one_eye: int
    # severe_headache: int
    # lump: int
    # unexplained_weight_loss: int
    # changes_in_bowel: int
    # bladder_habits: int
    # persistent_cough: int
    # indigestion: int
    # unexplained_bleeding_or_discharge: int
    # increased_thirst: int
    # frequent_urination: int
    # blurred_vision: int
    # cuts_that_are_slow_to_heal: int
    # memory_loss: int
    # difficulty_thinking: int
    # changes_in_personality_or_behavior: int
    # pain: int
    # stiffness: int
    # swelling: int
    # inflammation_in_the_joints: int
    # conjunctivitis: int
    # rash: int
    # pink_eye: int
    # diarrhea: int
    # jaundice: int
    # liver_damage: int
    # death: int
    # physical_dependence_on_alcohol: int
    # tolerance_to_alcohol: int
    # withdrawal_symptoms: int
    # impaired_judgment: int
    # memory_problems: int
    # heart_disease: int
    # cancer: int
    # runny_nose: int
    # sneezing: int
    # itchy_eyes: int
    # itchy_nose: int
    # throat: int
    # palate: int
    # excessive_worry: int
    # fear: int
    # anxiety_that_interfere_with_daily_life: int
    # pain_in_the_lower_right_abdomen: int
    # difficulty_with_social_interaction: int
    # repetitive_behaviors: int
    # restricted_interests: int
    # wheezing: int
    # coughing: int
    # chest_tightness: int
    # stiff_neck: int
    # sensitivity_to_light: int
    # extreme_mood_swings: int
    # from_manito_depression: int
    # blood_in_the_urine: int
    # pain_or_burning_when_urinating: int
    # urgency_to_urinate: int
    # incontinence: int
    # redness: int
    # warmth: int
    # tenderness_in_the_affected_area: int
    # difficulty_breathing: int
    # coughing_up_blood: int
    # inflammation_in_bursa: int
    # which_is_small_sac_of_fluid_that_cushions_joints: int
    # abnormal_pap_test_results: int
    # abnormal_vaginal_bleeding: int
    # pain_during_sex: int
    # chronic_bronchitis: int
    # emphysema: int
    # high_levels_of_cholesterol_in_the_blood: int
    # congestion: int
    # red: int
    # itchy: int
    # watery_eyes: int
    # sadness: int
    # hopelessness: int
    # loss_of_interest_in_activities: int
    # changes_in_appetite: int
    # sleep: int
    # energy_levels: int
    # loose: int
    # watery_stools: int
    # disturbance_in_eating_behavior_that_can_lead_to_serious_health_problems: int
    # seizures: int
    # elevated_body_temperature_: int
    # abdominal_cramps: int
    # pain_in_the_upper_right_abdomen: int
    # sexually_transmitted_infection_that_can_cause_burning_during_urination: int
    # discharge_from_the_penis_or_vagina: int
    # pain_in_the_lower_abdomen: int
    # dizziness: int
    # fainting: int
    # inflammation_of_the_liver: int
    # sexually_transmitted_infection_that_can_cause_blisters_on_the_genitals: int
    # mouth: int
    # other_parts_of_the_body: int
    # abdominal_pain: int
    # bloating: int
    # constipation: int
    # pain_in_the_lower_back_or_side: int
    # cough_that_does_not_go_away: int
    # blood_in_the_sputum: int
    # chills: int
    # red_eyes: int
    # swollen_lymph_nodes: int
    # tingling_at_the_bite_site: int
    # difficulty_swallowing: int
    # hydrophobia: int
    # aerophobia: int
    # painful_rash_that_follows_nerve_path: int
    # night_sweats: int
    # weight_loss: int
    # painful_urination: int
    # burning: int
    # swollen: int
    # twisted_veins: int
    # usually_in_the_legs: int
    # raised: int
    # rough_growths_on_the_skin: int
    # itching: int
    # discharge_from_the_vaginor_penis: int
    # inflammation_in_the_eye: int
    # decreased_kidney_function: int
    # pale_skin: int
    # bulge_in_the_wall_of_the_aorta: int
    # the_largest_artery_in_the_body: int
    # change_in_bowel_habits: int
    # such_as_diarrhea: int
    # narrowing_of_the_stool: int
    # blood_in_the_stool: int
    # difficulty_getting: int
    # keeping_an_erection_: int
    # widespread_pain: int
    # tenderness: int
    # increased_pressure_in_the_eye_that_can_damage_the_optic_nerve: int
    # lead_to_vision_loss: int
    # condition_in_which_the_heart_cannot_pump_blood_as_well_as_it_should: int
    # damage_to_the_kidneys_that_can_lead_to_kidney_failure: int
    # condition_that_affects_the_lungs: int
    # can_make_it_difficult_to_breathe: int
    # tremors: int
    # slow_movement: int
    # difficulty_with_balance: int
    # coordination_: int
    # pain_in_the_upper_abdomen: int
    # numbness: int
    # tingling_in_the_arms_or_legs: int
    # difficulty_urinating: int
    # pain_in_the_back_or_hips: int
    # erectile_dysfunction: int
    # stiffness_in_the_joints: int
    # lump_in_the_neck: int
    # hoarseness: int
    # unexplained_heat_intolerance: int
    # sensitivity_to_cold: int
    # bloody_stool: int
    # inflamed_skin: int
    # high_blood_pressure: int
    # changes_in_urination: int
    # hyperthyroidism: int
    # which_is_an_overactive_thyroid: int
    # hypothyroidism: int
    # which_is_an_underactive_thyroid_: int
    # chronic_autoimmune_disease_that_can_affect_any_part_of_the_body: int
